import { Geist, Geist_Mono } from "next/font/google";
import Footer from "./footer/page";
import "./globals.css";
import SideNavbar from "./componentssecond/SideNavBar"
import Navbar from "./componentssecond/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Main wrapper for full page layout */}
        <div className="page-container">
          {/* Main content area */}
          <div className="main-content">
          <SideNavbar/>
          <Navbar />
            {children}
          </div>
       
          <Footer />
        </div>
      </body>
    </html>
  );
}
